#pragma once

#define BUILDTYPE(name, ...) typedef enum { __VA_ARGS__ } name

BUILDTYPE(FlagType, ftC = 4, ftH = 5, ftN = 6, ftZ = 7);
BUILDTYPE(IntType, INTVBLANK, INTSTAT, INTTIMER, INTSERIAL, INTJOYPAD);
BUILDTYPE(PPUStateType, HBLANK, VBLANK, OAMSEARCH, PIXELTRANSFER);
BUILDTYPE(LCDCType, BGANDWINEN, OBJEN, OBJSIZE, BGTILEMAPAREA,
          BGANDWINTILEDATAAREA, WINEN, WINTILEMAPAREA, LCDPPUEN);
BUILDTYPE(LCDSType, PPUMODEBIT0, PPUMODEBIT1, COINCIDENCE, MODE0INT, MODE1INT,
          MODE2INT, LYCINT);
BUILDTYPE(MBCType, MBCt1);
