name: Linux-Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive
          
    - name: Setup System
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libltdl-dev libx11-dev libxft-dev libxext-dev
        version: 1.0

    - name: Setup Clang
      uses: egor-tensin/setup-clang@v1
      with:
       version: latest
       platform: x64
    
    - name: Install Dependencies
      run: |
        ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
        ./vcpkg/vcpkg install

    - name: Build
      run: |
        cmake --preset release
        cmake --build --preset release
        
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: Linux Executable
        path: './build/release/reGB'
